# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9013819ce2ec08dadc604cb96b2b454c5aa382b78256bb07d15a52261266a8869df538b717384629aae622abae88a039996ebf1a5a26de579adc4e899aefbb35

test:
  secret_key_base: 9346f16f9aaf81df6208da6958f0b8b1b83942021eb7af3c8e8906f6c3005572b4c555035801743c3a944548a6b4c1da2f91f8b4babe0b2ecece06ee760fd3f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
